Snippy.App/Models/ViewModels/SnippetViewModel.cs
namespace Snippy.App.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using AutoMapper;

    using Snippy.Infrastructure.Mappings;
    using Snippy.Models;

    public class SnippetViewModel : IMapFrom<Snippet>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public ProgrammingLanguageViewModel ProgrammingLanguage { get; set; }

        public DateTime CreatedAt { get; set; }

        public string AuthorId { get; set; }

        public string AuthorUsername { get; set; }

        public IEnumerable<LabelViewModel> Labels { get;set; }
        [UIHint("CommentForSnipperViewModel")]
        public IEnumerable<CommentViewModel> Comments { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Snippet, SnippetViewModel>()
                .ForMember(x => x.AuthorUsername, opt => opt.MapFrom(x => x.Author.UserName))
                .ReverseMap();
        }
    }
}

Snippy.App/Controllers/CommentsController.cs
namespace Snippy.App.Controllers
{
    using System;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;

    using Snippy.App.Models.BindingModels;
    using Snippy.App.Models.ViewModels;
    using Snippy.Data.UnitOfWork;
    using Snippy.Models;

    public class CommentsController : BaseController
    {
        public CommentsController(ISnippyData data)
            : base(data)
        {
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var comment = Mapper.Map<Comment>(model);
                comment.CreatedAt = DateTime.Now;
                comment.AuthorId = this.UserProfile.Id;
                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();
                var dbcomment = this.Data.Comments.Find(comment.Id);
                var viewModel = Mapper.Map<CommentViewModel>(dbcomment);
                return this.PartialView("DisplayTemplates/CommentForSnipperViewModel", new [] { viewModel });
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid input");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var comment = this.Data.Comments.Find(id);
            if (comment == null)
            {
                return this.HttpNotFound("Comment no longer exists");
            }

            var viewModel = Mapper.Map<CommentViewModel>(comment);
            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CommentViewModel model)
        {
            if (model != null)
            {
                this.Data.Comments.Delete(model.Id);
                this.Data.SaveChanges();
            }
            return this.RedirectToAction(
                "Details",
                "Snippets",
                new { id = model.SnippetId });
        }
    }
}

Snippy.App/Controllers/LabelsController.cs
namespace Snippy.App.Controllers
{
    using System.Web.Mvc;

    using AutoMapper;

    using Snippy.App.Models.ViewModels;
    using Snippy.Data.UnitOfWork;

    public class LabelsController : BaseController
    {
        public LabelsController(ISnippyData data)
            : base(data)
        {
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var label = this.Data.Labels.Find(id);
            if (label == null)
            {
                return this.HttpNotFound("Comment no longer exists");
            }

            var viewModel = Mapper.Map<DetailedLabelViewModel>(label);
            return this.View(viewModel);
        }
    }
}

Snippy.App/Controllers/LanguagesController.cs
namespace Snippy.App.Controllers
{
    using System.Web.Mvc;

    using AutoMapper;

    using Snippy.App.Models.ViewModels;
    using Snippy.Data.UnitOfWork;

    public class LanguagesController : BaseController
    {
        public LanguagesController(ISnippyData data)
            : base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var language = this.Data.ProgrammingLanguages.Find(id);
            if (language == null)
            {
                return this.HttpNotFound("Language no longer exists");
            }

            var viewModel = Mapper.Map<DetaildLanguageViewModel>(language);
            return this.View(viewModel);
        }
    }
}

Snippy.App/Controllers/SnippetsController.cs
namespace Snippy.App.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using Ninject.Infrastructure.Language;

    using PagedList;

    using Snippy.App.Models.BindingModels;
    using Snippy.App.Models.ViewModels;
    using Snippy.Common;
    using Snippy.Data.UnitOfWork;
    using Snippy.Infrastructure.Populators;
    using Snippy.Models;

    public class SnippetsController : BaseController
    {
        private IDropDownListPopulator populator;

        public SnippetsController(ISnippyData data, IDropDownListPopulator populator)
            : base(data)
        {
            this.populator = populator;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult All(int page = 1)
        {
            var allSnippets = 
                this.Data.Snippets.All()
                .OrderByDescending(s => s.CreatedAt)
                .ThenBy(s => s.Title)
                .ProjectTo<SnippetViewModel>();

            return this.View(allSnippets.ToPagedList(page, GlobalConstants.DefaultPageSize));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var snippet = this.Data.Snippets.Find(id);
            if (snippet == null)
            {
                return this.HttpNotFound("The snippet you are looking for has been removed");
            }

            var snippetViewModel = Mapper.Map<SnippetViewModel>(snippet);
            return this.View(snippetViewModel);
        }

        [HttpGet]
        public ActionResult My()
        {
            var loggedUserSnippets =
                this.Data.Snippets.All()
                    .OrderByDescending(s => s.CreatedAt)
                    .Where(s => s.AuthorId == this.UserProfile.Id)
                    .ProjectTo<SnippetViewModel>();
            return this.View(loggedUserSnippets);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var snippetBindinModel = new SnippetBindingModel();
            this.PopulateLangues(snippetBindinModel);
            return this.View(snippetBindinModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SnippetBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var snippet = Mapper.Map<Snippet>(model);
                snippet.AuthorId = this.UserProfile.Id;
                snippet.CreatedAt = DateTime.Now;
                var labels = this.GetLabels(model.LabelsAsText);
                this.PopulateLabelsToSnippet(snippet, labels);
                this.Data.Snippets.Add(snippet);
                snippet.ProgrammingLanguage =
                    this.Data.ProgrammingLanguages.All()
                        .FirstOrDefault(
                            x => x.Id == model.ProgrammingLanguageId);
                this.Data.SaveChanges();
                return this.RedirectToAction("Details", new { id = snippet.Id });
            }
            this.PopulateLangues(model);
            return this.View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var snippet = this.Data.Snippets.Find(id);
            if (snippet == null)
            {
                return this.HttpNotFound("Snippet no longer exists");
            }
            var model = Mapper.Map<SnippetBindingModel>(snippet);
            this.PopulateLangues(model);
            var labelsText = string.Empty;
            foreach (var label in snippet.Labels)
            {
                labelsText += label.Text + ";";
            }
            model.LabelsAsText = labelsText;
            return this.View( model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SnippetBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var snippet = this.Data.Snippets.Find(model.Id);
                snippet.Title = model.Title;
                snippet.Code = model.Code;
                snippet.Description = model.Description;
                snippet.ProgrammingLanguageId = model.ProgrammingLanguageId;

                var labels = this.GetLabels(model.LabelsAsText);
                this.AttachNewLabels(snippet, labels);
                this.Data.Snippets.Add(snippet);
                snippet.ProgrammingLanguage =
                    this.Data.ProgrammingLanguages.All()
                        .FirstOrDefault(
                            x => x.Id == model.ProgrammingLanguageId);
                this.Data.SaveChanges();
                return this.RedirectToAction("Details", new { id = snippet.Id });
            }
            this.PopulateLangues(model);
            return this.View(model);
        }

        private void AttachNewLabels(Snippet snippet, string[] labels)
        {
            foreach (var labelText in labels)
            {
                if (!snippet.Labels.Any(l => l.Text == labelText))
                {
                    var label = new Label() { Text = labelText };
                    label.Snippets.Add(snippet);
                    this.Data.Labels.Add(label);
                    this.Data.SaveChanges();
                }
            }
        }

        private void PopulateLabelsToSnippet(Snippet snippet, string[] labels)
        {
            foreach (var labelText in labels)
            {
                if (!this.LabelExists(labelText))
                {
                    var label = new Label() { Text = labelText };
                    this.Data.Labels.Add(label);
                    this.Data.SaveChanges();
                    snippet.Labels.Add(label);
                }
                else
                {
                    var label = this.Data.Labels.All().FirstOrDefault(x => x.Text == labelText);
                    label.Snippets.Add(snippet);
                }
            }
        }

        private string[] GetLabels(string labelsAsText)
        {
            string[] labelsArr = Regex.Split(labelsAsText, @" *; *");
            labelsArr = labelsArr.Where(x => x != string.Empty).ToArray();
            return labelsArr;
        }

        private bool LabelExists(string text)
        {
            return this.Data.Labels.All().Any(l => l.Text == text);
        }

        private void PopulateLangues(SnippetBindingModel model)
        {
            model.Languages = this.populator.GetLanguages();
        }
    }
}

Snippy.App/Views/Snippets/All.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Snippy.App.Models.ViewModels.SnippetViewModel>
@{
    ViewBag.Title = "All";
}
<div class="well">
    <h2 class="text-center">All snippets</h2>
</div>
<div class="well row">
    <div class="col-sm-10 col-md-offset-1">
        @Html.DisplayFor(m => m)
    </div>
    <p>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>

    @Html.PagedListPager(Model, page => Url.Action("All",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>

Snippy.App/Views/Snippets/Create.cshtml
@model Snippy.App.Models.BindingModels.SnippetBindingModel
@{
    ViewBag.Title = "Add new snippet";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Snippets", FormMethod.Post, new {@class = "form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.EditorFor(x=>x.Title)
    @Html.EditorFor(x=>x.Description)
    @Html.EditorFor(x=>x.Code)
    @Html.EditorFor(a => a.ProgrammingLanguageId, new { ListItem = Model.Languages })
    @Html.EditorFor(x => x.LabelsAsText)

    <input type="submit" value="Add" class="btn btn-success"/>
    @Html.ActionLink("Cancel", "Index", "Home", null, new {@class = "btn btn-default"})
}

<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

Snippy.App/Views/Snippets/Details.cshtml
@using Microsoft.AspNet.Identity
@model Snippy.App.Models.ViewModels.SnippetViewModel
@{
    ViewBag.Title = "Details";
}

<h2 class="text-center">Snippet details</h2>
<div class="row">
    <div class="col-sm-10 col-md-offset-1">
        <h2>
            @Html.ActionLink(Model.ProgrammingLanguage.Name, "Details", "Languages", new { id = Model.ProgrammingLanguage.Id }, new { @class = "btn btn-success" })
            @Model.Title
            @if (Model.AuthorId == User.Identity.GetUserId())
            {
                @Html.ActionLink("Edit", "Edit", "Snippets", new { id = Model.Id }, new { @class = "btn btn-warning" })
            }
        </h2>
        <p>
            by :<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <strong>@Model.AuthorUsername </strong> on @Model.CreatedAt.ToShortDateString()
        </p>
        <p>
            Labels:
            @foreach (var label in Model.Labels)
            {
                <span> @Html.ActionLink(label.Text, "Details", "Labels", new { id = label.Id }, new { @class = "label label-primary" })</span>
            }
        </p>
        <p>@Model.Description</p>
        <div class="well">
            <pre><code>@Model.Code</code></pre>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <span class="badge">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                    <span id="snippetCommentsCount">@Model.Comments.Count()</span> comments
                </span>
            </div>
        </div>
        <h3>Comments: </h3>
        @if (User.Identity.IsAuthenticated)
        {
            using (Ajax.BeginForm("Create", "Comments", new { }, new AjaxOptions()
            {
                HttpMethod = "POST",
                UpdateTargetId = "commentsContainer",
                InsertionMode = InsertionMode.InsertAfter,
                OnSuccess = "hideLabels"
            }, null))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("SnippetId", Model.Id)
                @Html.TextArea("Content", "", new { @class = "form-control", placeholder = "Write a public comment..." })
                <input type="submit" value="Add comment" class="btn btn-primary" />
            }
        }
        <hr />
        <div id="commentsContainer">
            @if (Model.Comments.Any())
            {

                @Html.DisplayFor(x => x.Comments, "CommentForSnipperViewModel")

            }
            else
            {
                <p class="no-comments-label">There are no comments right now.</p>
            }
        </div>
    </div>
</div>
<script>
    function hideLabels() {
        var snippetComments = $("#snippetCommentsCount");
        var val = snippetComments.text();
        snippetComments.text(parseInt(val) + 1);
        $(".no-comments-label").hide();
        $("#Content").val("");
    }
</script>

Snippy.App/Views/Snippets/Edit.cshtml
@model Snippy.App.Models.BindingModels.SnippetBindingModel
@{
    ViewBag.Title = "Edit snippet";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Snippets", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.EditorFor(x => x.Title)
    @Html.EditorFor(x => x.Description)
    @Html.EditorFor(x => x.Code)
    @Html.EditorFor(a => a.ProgrammingLanguageId, new { ListItem = Model.Languages })
    @Html.EditorFor(x => x.LabelsAsText)

    <input type="submit" value="Edit" class="btn btn-success" />
    @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-default" })
}

Snippy.App/Views/Snippets/My.cshtml
@model IEnumerable<Snippy.App.Models.ViewModels.SnippetViewModel>
@{
    ViewBag.Title = "My snippets";
}

<div class="row">
    <div class="col-sm-10 col-md-offset-1">
        <h2>@ViewBag.Title</h2>
        <hr />
        @if (Model.Any())
        {
            @Html.DisplayFor(x => x)
        }
        else
        {
            <p>
                You have no snippets. You can
                @Html.ActionLink("create", "Create", "Snippets")
                one now.
            </p>
        }
    </div>
</div>